---
- hosts: database
  roles:
     - postgres
     - create_database
- hosts: cache
  roles:
     - redis-cluster
- hosts: cluster_starter
  roles:
     - cluster_starter
- hosts: security
  become: yes
  become_user: root
  roles:
    - angstwad.docker_ubuntu
    - security-application
- hosts: ui
  become: yes
  become_user: root
  roles:
    - angstwad.docker_ubuntu
    - security-application
