# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">= 1.7.0"

Vagrant.configure("2") do |config|

  (1..4).each do |i|
    config.vm.define "node-#{i}" do |node|
       node.ssh.insert_key = false
       node.vm.network "private_network", ip: "192.168.77.#{20+i}"
       node.vm.box = "ubuntu/trusty64"
       node.vm.provider "virtualbox" do |vb|
         vb.memory = "1024"
       end
       node.vm.provision "ansible" do |ansible|
         ansible.verbose = "v"
         ansible.playbook = "playbook.yml"
         ansible.groups = {
           "web" => ["vm1", "vm2"],
           "db"  => ["vm3"]
         }
         ansible.extra_vars = {
           redis_port: "#{6377 + i}"
         }
       end
     end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
    ansible.groups = {
      "cache" => ["node-2", "node-3", "node-4"],
      "database"  => ["node-1"]
    }
  end

end
