# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">= 1.7.0"

Vagrant.configure("2") do |config|

  (1..3).each do |i|
    config.vm.define "node-#{i}" do |node|
       node.ssh.insert_key = false
       node.vm.network "private_network", ip: "192.168.77.#{20+i}"
       node.vm.box = "ubuntu/trusty64"
       node.vm.provider "virtualbox" do |vb|
         vb.memory = "1024"
       end
     end
  end

  config.vm.define "node-1" do |node|
    node.ssh.insert_key = false

    node.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "database.yml"
    end
  end

end
