jwt:
  path: classpath:mytest.jks
  key-pass: mypass
  store-pass: mypass
  alias: mytest
spring:
  redis.cluster.nodes: 192.168.77.22:6379, 192.168.77.23:6379, 192.168.77.24:6379
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://192.168.77.21:5432/oauth
    username: application
    password: mysecretpassword
    platform: postgres
    driverClassName: org.postgresql.Driver
logging:
  file: log/application.log