jwt:
  path: classpath:mytest.jks
  key-pass: mypass
  store-pass: mypass
  alias: mytest
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://192.168.77.21:5432/postgres
    username: application
    password: mysecretpassword
    platform: postgres
    driverClassName: org.postgresql.Driver
logging:
  file: log/application.log