jwt:
  path: classpath:mytest.jks
  key-pass: mypass
  store-pass: mypass
  alias: mytest
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    platform: postgres
    driverClassName: org.postgresql.Driver
