oauth.connection:
  authorization_url: http://localhost:8081/oauth/authorize
  token_url: http://localhost:8081/oauth/token
  client_id: newClient
  client_secret: secret
  redirect_url: http://localhost:8080/login
