---
# tasks file for postgres
  - name: install postgres
    become: yes
    become_user: root
    apt:
      name: postgresql
      state: latest
      update_cache: yes
  - name: install libpq-dev
    become: yes
    become_user: root
    apt:
      name: libpq-dev
      state: latest
  - name: install python-psycopg2
    become: yes
    become_user: root
    apt:
      name: python-psycopg2
      state: latest
  - name: install postgresql-contrib
    become: yes
    become_user: root
    apt:
      name: postgresql-contrib
      state: latest
  - name: copy pg_hba.conf
    become: yes
    become_user: postgres
    copy:
      src: pg_hba.conf
      dest: /etc/postgresql/9.3/main/pg_hba.conf
  - name: copy postgresql.conf
    become: yes
    become_user: postgres
    copy:
      src: postgresql.conf
      dest: /etc/postgresql/9.3/main/postgresql.conf
  - name: init service
    become: yes
    become_user: root
    service:
      name: postgresql
      state: restarted
